### ISSUE TITLE
Сolor scheme for rofi

### ISSUE THREAD

**Issue by MuratovAS** [ericmurphyxyz/rofi-wifi-menu#1]
Can you share a color scheme for `rofi`?
I think not to me alone it is interesting, so it is advisable to add information about it in `Readme.md`

**Comment by ProgrammingLife** [comment]
The same here. I've also been inspired by that color scheme. It would be nice to see your rofi config if this possible.

**Comment by abdoulayegk** [comment]
Hey check out my dotefiles I have almost same rofi config https://github.com/abdoulayegk/dotefiles.
